language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip install unittest2

env:
  - COVERAGE_FILE=".coverage" FLASK_APP="main_app.py" SECRET="i wont tell if you dont" APP_SETTINGS="testing" TEST_DB_URL="postgres://postgres@localhost/test_db"
services:
  - postgresql
before_script:
  - "psql -c 'create database test_db;' -U postgres"

script:
  - "python manage.py test"