language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip install unittest2

env:
  - FLASK_APP="main_app.py" USER_SECRET_KEY="i wont tell if you dont" ADMIN_SECRET_KEY="secret" config_name="testing" SQLALCHEMY_DATABASE_URI="postgresql://josekodek:kevina52@localhost:5432/foodhubtesting"

services:
  - postgresql

before_script:
  - "psql -c 'create database test_db;' -U postgres"

script:
  - "python manage.py test"